import type { Metadata } from 'next';
import getCurrentUser from '@/app/actions/getCurrentUser';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Front',
  description: 'Generated by create next app',
};

export default async function FrontLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await getCurrentUser();

  return (
    <>
      <Header currentUser={currentUser} />
      {children}
    </>
  );
}
